name: scrapbook
description: HackClub Scrapbook Flutter Client.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  mobx: ^1.2.1
  timeago: ^2.0.26
  retrofit: ^1.3.4
  provider: ^4.0.4
  typeweight: ^0.0.2
  flutter_mobx: ^1.1.0
  flutter_emoji: ^2.2.1+1
  json_annotation: ^3.0.1
  flutter_markdown: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0
  json_serializable: ^3.3.0
  retrofit_generator: ^1.3.7
  flutter_launcher_icons: ^0.7.4

scripts: derry.yaml

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Plus Jakarta Display
      fonts:
        - asset: fonts/PlusJakartaDisplay/PlusJakartaDisplay-Light.ttf
        - asset: fonts/PlusJakartaDisplay/PlusJakartaDisplay-LightItalic.ttf
          style: italic
        - asset: fonts/PlusJakartaDisplay/PlusJakartaDisplay-Regular.ttf
        - asset: fonts/PlusJakartaDisplay/PlusJakartaDisplay-Italic.ttf
          style: italic
        - asset: fonts/PlusJakartaDisplay/PlusJakartaDisplay-Medium.ttf
        - asset: fonts/PlusJakartaDisplay/PlusJakartaDisplay-MediumItalic.ttf
          style: italic
        - asset: fonts/PlusJakartaDisplay/PlusJakartaDisplay-Bold.ttf
        - asset: fonts/PlusJakartaDisplay/PlusJakartaDisplay-BoldItalic.ttf
          style: italic
